const dsaTrackerList = [ 
    { 
        title: "HTML", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to HTML", completed: false }, 
            { subtitle: "HTML Elements", completed: false }, 
            { subtitle: "HTML Forms", completed: false }, 
            { subtitle: "HTML Attributes", completed: false }, 
            { subtitle: "HTML Tables", completed: false },
            { subtitle: "HTML Semantic Elements", completed: false },
            { subtitle: "HTML Media", completed: false },
            { subtitle: "HTML5 New Features", completed: false },
            { subtitle: "HTML Best Practices", completed: false },
        ], 
    }, 
    { 
        title: "CSS", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to CSS", completed: false }, 
            { subtitle: "CSS Selectors", completed: false }, 
            { subtitle: "CSS Flexbox", completed: false }, 
            { subtitle: "CSS Grid", completed: false },
            { subtitle: "CSS Animations", completed: false },
            { subtitle: "CSS Transitions", completed: false },
            { subtitle: "CSS Variables", completed: false },
            { subtitle: "CSS Pseudo-classes and Pseudo-elements", completed: false },
            { subtitle: "Responsive Design with CSS", completed: false },
        ], 
    }, 
    { 
        title: "Bootstrap", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to Bootstrap", completed: false }, 
            { subtitle: "Bootstrap Grid System", completed: false }, 
            { subtitle: "Bootstrap Components", completed: false }, 
            { subtitle: "Bootstrap Utilities", completed: false },
            { subtitle: "Bootstrap Forms", completed: false },
            { subtitle: "Bootstrap Modals", completed: false },
            { subtitle: "Bootstrap Navbar", completed: false },
            { subtitle: "Bootstrap Carousel", completed: false },
            { subtitle: "Customizing Bootstrap", completed: false },
        ], 
    }, 
    { 
        title: "JavaScript", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to JavaScript", completed: false }, 
            { subtitle: "JavaScript Functions", completed: false }, 
            { subtitle: "JavaScript DOM Manipulation", completed: false },
            { subtitle: "JavaScript Events", completed: false },
            { subtitle: "JavaScript Asynchronous Programming", completed: false },
            { subtitle: "JavaScript Promises", completed: false },
        ], 
    }, 
    { 
        title: "Node.js", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to Node.js", completed: false }, 
            { subtitle: "Node.js Modules", completed: false }, 
            { subtitle: "Node.js File System", completed: false }, 
            { subtitle: "Node.js Events", completed: false },
            { subtitle: "Node.js Streams", completed: false },
            { subtitle: "Node.js HTTP Module", completed: false },
            { subtitle: "Node.js Express Framework", completed: false },
        ], 
    }, 
    { 
        title: "Express.js", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to Express.js", completed: false }, 
            { subtitle: "Express.js Routing", completed: false }, 
            { subtitle: "Middleware in Express.js", completed: false }, 
            { subtitle: "Building RESTful APIs with Express.js", completed: false },
            { subtitle: "Express.js with MongoDB", completed: false },
            { subtitle: "Authentication with Express.js", completed: false },
            { subtitle: "Error Handling in Express.js", completed: false },
        ], 
    }, 
    { 
        title: "React.js", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to React.js", completed: false }, 
            { subtitle: "React Components", completed: false }, 
            { subtitle: "State and Props in React.js", completed: false }, 
            { subtitle: "React Hooks", completed: false },
            { subtitle: "React Router", completed: false },
            { subtitle: "Managing State with Redux", completed: false },
            { subtitle: "React Context API", completed: false },
        ], 
    }, 
    { 
        title: "MongoDB", 
        progress: 0, 
        subsections: [ 
            { subtitle: "Introduction to MongoDB", completed: false }, 
            { subtitle: "CRUD Operations in MongoDB", completed: false }, 
            { subtitle: "Aggregation Framework in MongoDB", completed: false }, 
            { subtitle: "Indexing and Performance in MongoDB", completed: false },
            { subtitle: "Data Modeling in MongoDB", completed: false },
            { subtitle: "Replication and Sharding in MongoDB", completed: false },
            { subtitle: "Security in MongoDB", completed: false },
        ], 
    }, 
]; 
  
export default dsaTrackerList;
